package com.project.cinemarest.model;

import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ClientInfo {
    //customer info to make transaction valid
    private UUID userId;

    private String cardNumber;

    private String expirationDate;

    private String cvc;

    //Movie chosen by the customer
    private Integer idMovie;

    //Autogenerated unique ticket id
    private Long ticketId;

    //Seat chosen by the customer
    private String[] seats;

    private Double totalPrice;
}
